/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import entities.GPSTracker;
import entities.Vehicule;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import service.VehiculeService;
import service.GPSTrackerService;
import service.VehiculeGPSTrackerService;

/**
 *
 * @author Lachgar
 * @author Kadem
 *
 */
public class VehiculeForm extends javax.swing.JInternalFrame {

    private GPSTrackerService ts;
    private VehiculeService vs;
    private VehiculeGPSTrackerService vgs;
    private DefaultTableModel model;
    private static int id;

    /**
     * Creates new form VehiculeForm
     */
    public VehiculeForm() {
        setResizable(true);
        initComponents();
        model = (DefaultTableModel) vehiculesTable.getModel();
        ts = new GPSTrackerService();
        vs = new VehiculeService();
        vgs = new VehiculeGPSTrackerService();
        loadVehicules();
    }

    private void loadVehicules() {
        model.setRowCount(0);
        for (Vehicule v : vs.findAll()) {
            model.addRow(new Object[]{
                v.getId(),
                v.getMarque(),
                v.getMatricule(),
                v.getType(),
                v.getVehiculeGPSTracker()
            });

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        marqueTxt = new javax.swing.JTextField();
        matriculeTxt = new javax.swing.JTextField();
        typeTxt = new javax.swing.JTextField();
        bnDelete = new javax.swing.JButton();
        bnEdit = new javax.swing.JButton();
        BnAdd = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        vehiculesTable = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("list des voiture");

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel2.setText("Marque");

        jLabel3.setText("Matricule");

        jLabel4.setText("Type");

        marqueTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marqueTxtActionPerformed(evt);
            }
        });

        bnDelete.setText("supprimer");
        bnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnDeleteActionPerformed(evt);
            }
        });

        bnEdit.setText("modifier");
        bnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnEditActionPerformed(evt);
            }
        });

        BnAdd.setText("ajouter");
        BnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(marqueTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BnAdd)
                            .addComponent(typeTxt))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(bnDelete)
                        .addGap(44, 44, 44)
                        .addComponent(bnEdit))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addGap(41, 41, 41)
                        .addComponent(matriculeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(178, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(marqueTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matriculeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bnDelete)
                    .addComponent(bnEdit)
                    .addComponent(BnAdd))
                .addGap(23, 23, 23))
        );

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        vehiculesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "matricule", "marque", "type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        vehiculesTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vehiculesTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(vehiculesTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addGap(0, 0, 0))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void marqueTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marqueTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marqueTxtActionPerformed

    private void bnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnDeleteActionPerformed
        // TODO add your handling code here:
        int reponse = JOptionPane.showConfirmDialog(this, "Voulez vous vraiment supprimer ce tracker");
        if (reponse == 0 && id != 0) {
            if (vs.delete(vs.findById(id))) {
                JOptionPane.showMessageDialog(this, "Vehicule supprimé");
                loadVehicules();
            } else {
                JOptionPane.showMessageDialog(this, "suppression impossible");

            }
        }
    }//GEN-LAST:event_bnDeleteActionPerformed

    private void bnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnEditActionPerformed
        // TODO add your handling code here:
        Vehicule v = vs.findById(id);
        v.setMarque(marqueTxt.getText());
        v.setMatricule(matriculeTxt.getText());
        v.setType(typeTxt.getText());
        int reponse = JOptionPane.showConfirmDialog(this, "Voulez vous vraiment modifier cette voiture");

        if (reponse == 0 && id != 0) {
            if (vs.update(v)) {
                JOptionPane.showMessageDialog(this, "Tracker modifié");
                loadVehicules();
            }
        }
    }//GEN-LAST:event_bnEditActionPerformed

    private void vehiculesTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vehiculesTableMouseClicked
        // TODO add your handling code here:
           id = Integer.parseInt(model.getValueAt(vehiculesTable.getSelectedRow(), 0).toString());
        matriculeTxt.setText(model.getValueAt(vehiculesTable.getSelectedRow(), 1).toString());
        marqueTxt.setText(model.getValueAt(vehiculesTable.getSelectedRow(), 2).toString());
        typeTxt.setText( model.getValueAt(vehiculesTable.getSelectedRow(), 3).toString());
    }//GEN-LAST:event_vehiculesTableMouseClicked

    private void BnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BnAddActionPerformed
        // TODO add your handling code here:
        String marque =marqueTxt.getText();
        String matricule = matriculeTxt.getText();
        String type = typeTxt.getText();
        Vehicule v = new Vehicule(matricule, marque, type);
            if (vs.create(v)) {
                JOptionPane.showMessageDialog(this, "Vehicule ajouté");
                loadVehicules();
            }
        
    }//GEN-LAST:event_BnAddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BnAdd;
    private javax.swing.JButton bnDelete;
    private javax.swing.JButton bnEdit;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField marqueTxt;
    private javax.swing.JTextField matriculeTxt;
    private javax.swing.JTextField typeTxt;
    private javax.swing.JTable vehiculesTable;
    // End of variables declaration//GEN-END:variables
}
